# Generated by Django 3.2.4 on 2022-04-25 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('res_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='Rental',
            new_name='rental',
        ),
    ]
