# Generated by Django 3.2.4 on 2022-04-25 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('res_app', '0002_rename_rental_reservation_rental'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='rental',
            new_name='rental_id',
        ),
    ]
