# Generated by Django 3.2.4 on 2022-04-26 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('res_app', '0004_rename_rental_id_reservation_rental'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='Rental',
            new_name='rental',
        ),
    ]
